spring.application.name=portalFeedback

spring.datasource.url=jdbc:postgresql://localhost:5432/RND
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.security.user.name=admin
spring.security.user.password=admin123

spring.jpa.hibernate.ddl-auto=update
